name: func-adl.xAOD-dev
channels:
  - conda-forge
  - defaults

dependencies:
  - flake8
  - python==3.7.4
  - pip
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pandas~=0.24
  - uproot~=3.7
  - pip:
    - git+https://github.com/iris-hep/ast-language.git@e6470deb68529e1885a4bc46f781e2fe43a6f4c8
    - requests~=2.0
    - retry~=0.9
    - func-adl.ast==1.0.0a17
    - jinja2
