name: func-adl.xAOD-dev
channels:
  - conda-forge
  - defaults

dependencies:
  - flake8
  - python>=3.7
  - pip
  - pytest
  - pip:
    - git+https://github.com/iris-hep/ast-language.git@4c16669eb3bb8830349a947a199f617a4b491240
